functions:
  ipv4:
  - name: ip_local_deliver
    args:
    - struct sk_buff *skb

  - name: ip_rcv
    args:
    - struct sk_buff *skb

  - name: ip_local_out
    args:
    - struct net *net
    - struct sock *sk
    - struct sk_buff *skb

  - name: ip_output
    args:
    - struct net *net
    - struct sock *sk
    - struct sk_buff *skb

  - name: ip_forward
    args:
    - struct sk_buff *skb

  - name: ip_route_input_noref
    args:
    - struct sk_buff *skb
    - __be32 daddr
    - __be32 saddr
    - u8 tos
    - struct net_device *dev

  - name: ip_build_and_send_pkt
    args:
    - struct sk_buff *skb
    - const struct sock *sk
    - __be32 saddr
    - __be32 daddr
    - void *opt

  - name: __ip_queue_xmit
    args:
    - struct sock *sk
    - struct sk_buff *skb
    - const struct flowi4 *fl4
    - __u8 tos

  - name: ip_do_fragment
    args:
    - struct net *net
    - struct sock *sk
    - struct sk_buff *skb
    - int (*output)(struct net *, struct sock *, struct sk_buff *)

  - name: ip_send_skb
    args:
    - struct net *net
    - struct sk_buff *skb

  ipv6:
  - name: ipv6_rcv
    args:
    - struct sk_buff *skb

  - name: ip6_input
    args:
    - struct sk_buff *skb

  - name: ip6_output
    args:
    - struct net *net
    - struct sock *sk
    - struct sk_buff *skb

  - name: ip6_local_out
    args:
    - struct net *net
    - struct sock *sk
    - struct sk_buff *skb

  - name: ip6_forward
    args:
    - struct sk_buff *skb

  - name: ipv6_rthdr_rcv
    args:
    - struct sk_buff *skb
